// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MashtiHasanRestaurant.DataLayer.Entities;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string CustomerName { get; set; }

    public string ContactTitle { get; set; }

    public string Mobile { get; set; }

    public string Tel { get; set; }

    public string Address { get; set; }

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();
}