// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MashtiHasanRestaurant.DataLayer.Entities;

public partial class OrderDetails
{
    public int OrderDetailsId { get; set; }

    public int OrderId { get; set; }

    public int FoodId { get; set; }

    public int UnitPrice { get; set; }

    public int Quantity { get; set; }

    public int TotalPrice { get; set; }

    public virtual Food Food { get; set; }

    public virtual Orders Order { get; set; }
}