// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MashtiHasanRestaurant.DataLayer.Entities;

public partial class Orders
{
    public int OrderId { get; set; }

    public DateTime OrderDate { get; set; }

    public string OrderDescription { get; set; }

    public int CustomerId { get; set; }

    public string Address { get; set; }

    public string Mobile { get; set; }

    public int EmployeeId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();
}